<?php

/**
 * @file
 * Module Name Helper main file.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function module_name_helper_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_theme().
 */
function module_name_helper_theme($existing, $type, $theme, $path) {
  return array(
    'file_upload' => array(
      'path' => "$path/templates",
      'template' => 'file-upload',
      'variables' => array(
        'file_upload_title' => '',
        'file_upload_image' => '',
        'file_upload_body' => '',
        'file_upload_button' => '',
      ),
    ),
    'back_button' => array(
      'path' => "$path/templates",
      'template' => 'back-button',
    ),
    'create_button' => array(
      'path' => "$path/templates",
      'template' => 'create-button',
      'variables' => array(
        'button_title' => '',
        'button_type' => '',
        'anchor_attributes' => '',
        'span_attributes' => '',
      ),
    ),
    'site_logo' => array(
      'path' => "$path/templates",
      'template' => 'site-logo',
      'variables' => array(
        'to_frontpage' => '/',
        'logo_src' => '',
      ),
    ),
  );
}
